 <!-- footer -->

<!-- Showrom -->
<div class="session-showrom">
    <div class="row">
        <div class="col-mb-4">
            <div class="showrom-img some-img"><img
                    src="{{media url="wysiwyg/image_showroom_footer/outdoor_Elegance.png"}}"
                    alt="Outdoor Elegance Logo"></div>
        </div>
        <div class="col-mb-4">
            <div class="showrom-Canberra"><a class="canberra-link action secondary" href="#">Canberra Showroom</a>
                <div class="style-guide-paragraph">
                    <p>Maryborough St &amp; Wollongong Street, Fyshwick ACT 2609 T: 1300 6</p>
                </div>
                <a class="web-link links-info" href="#">Text link</a>
            </div>
        </div>
        <div class="col-mb-4">
            <div class="showrom-img some-img"><img src="{{media url="wysiwyg/image_showroom_footer/webstore_logo.png"}}"
                    alt="Web Store Logo"></div>
        </div>
    </div>
</div>
<!-- End showrom -->

<!-- Footer banner-->
<div class="session-footer-banner">
    <div class="backgroud-color">
        <div class="footer-banner backgroud-img"
            style="background-image: url('{{media url="wysiwyg/image_backgroud_footer/backgroud-banner-min.png"}}');">
            <div class="content-banner">
                <h1 class="title-banner">Exclusive outdoor furniture, online prices</h1>
                <div class="style-guide-paragraph">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore
                        et dolore magna aliqua.
                    </p>
                    <a class="web-link links-banner" href="#">View more infor</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End footer banner-->

<!-- footer top -->
<div class="footer-top">
    <div class="row">
        <div class="col-mb-3">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-truck">&nbsp;</i>
                </div>
                <span class="text">We ship australia wide!</span>
            </div>
        </div>
        <div class="col-mb-3">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-location-dot">&nbsp;</i>
                </div>
                <span class="text">Find a store</span>
            </div>
        </div>
        <div class="col-mb-3">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-dollar-sign">&nbsp;</i>
                </div>
                <span class="text">Money back guarantee</span>
            </div>
        </div>
        <div class="col-mb-3">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-envelope">&nbsp;</i>
                </div>
                <span class="text">Contact us</span>
            </div>
        </div>
    </div>
</div>
<!-- end footer top -->

<!-- Footer links desktop-->
<div class="footer-links-desktop">
    <div class="row">
        <div class="col-mb-4">
            <div class="footer-links">
                <h3>Category</h3>
                <ul class="nav-link">
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-mb-4">
            <div class="footer-links">
                <h3>Why Burning Log?</h3>
                <ul class="nav-link">
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-mb-4">
            <div class="footer-links">
                <h3>Out Policies</h3>
                <ul class="nav-link">
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- end Footer links desktop-->

<!-- Newletter-->
<div class="footer-links-newsletter">
    <h3>Newsletter</h3>
    <ul>
        <li><a>Subscribe to our newsletter for the latest news and updates</a></li>
    </ul>
</div>
<!-- End Newletter-->

<!-- nav icon -->
<div class="nav-footer-icon">
    <div class="icon-item">
        <div class="social-icon"><a href="#"><i class="fab fa-facebook-f">&nbsp;</i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-instagram">&nbsp;</i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-twitter">&nbsp;</i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-brands fa-youtube">&nbsp;</i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-brands fa-pinterest">&nbsp;</i></a></div>
    </div>
</div>
<!-- end nav icon -->

<!-- Footer links mobile-->
<div id="accordion" class="footer-links-mobile" data-mage-init="{
        "accordion":{
            "active": [0],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}">
<div data-role="collapsible">
<div data-role="trigger">
<h3>Category <span class="minus"><em class="fa-solid fa-xmark">&nbsp;</em></span><span class="plus"><em class="fa-solid fa-plus">&nbsp;</em></span></h3>
</div>
</div>
<div data-role="content">
<ul class="nav-link">
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}</li>
</ul>
</div>
<div data-role="collapsible">
<div data-role="trigger">
<h3>Why Burning Log? <span class="minus"><em class="fa-solid fa-xmark">&nbsp;</em></span><span class="plus"><em class="fa-solid fa-plus">&nbsp;</em></span></h3>
</div>
</div>
<div data-role="content">
<ul class="nav-link">
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}</li>
</ul>
</div>
<div data-role="collapsible">
<div data-role="trigger">
<h3>Our Policies <span class="minus"><em class="fa-solid fa-xmark">&nbsp;</em></span><span class="plus"><em class="fa-solid fa-plus">&nbsp;</em></span></h3>
</div>
</div>
<div data-role="content">
<ul class="nav-link">
<li><a>Subscribe to our newsletter for the latest news and updates</a></li>
</ul>
</div>
</div>
<!-- End Footer links mobile-->
<!-- End Footer links mobile-->

<!-- img logo footer -->
<div class="logo-footer">
    <div class="img-item"><img src="{{media url="wysiwyg/image_logo_footer/Layer_572.png"}}" alt=""></div>
    <div class="img-item"><img src="{{media url="wysiwyg/image_logo_footer/PayPal.jpg"}}" alt=""></div>
    <div class="img-item"><img src="{{media url="wysiwyg/image_logo_footer/Visa.png"}}" alt=""></div>
    <div class="img-item"><img src="{{media url="wysiwyg/image_logo_footer/Mastercard.png"}}" alt=""></div>
    <div class="img-item"><img src="{{media url="wysiwyg/image_logo_footer/American-express.png"}}" alt=""></div>
</div>
<!-- end img logo footer -->