<div class="header-pc">
    <div class="header-contact">
        Contactus / <a href="">1300 660 330</a>
    </div>
    <div class="header-info">
        <ul>
            <li><a href="">Outdor Furniture</a></li>
            <li><a href="">Fireplaces</a></li>
            <li><a href="">Weber BBQs</a></li>
            <li><a href="">Canberra Showroom Open 7 Days</a></li>
        </ul>
    </div>
    <div class="header-more">
        <ul>
            <li><a href=""><i class="fa-brands fa-facebook-f"></i></a></li>
            <li><a href=""><i class="fa-brands fa-instagram"></i></a></li>
            <li><a href="">Blog</a></li>
        </ul>
    </div>
</div>


<div class="header-mobile">
    <div class="item-header left">
        <i class="fa-solid fa-location-dot"></i>
        <a href="">Canberra Showroom Open 7 Days</a>
    </div>
    <div class="item-header right">
        <i class="fa-solid fa-phone"></i>
        <a href="">1300 660 330</a>
    </div>
</div>