<div for="lastname" generated="true" class="mage-error" id="lastname-error">Please enter a valid email address</div>

<!-- *****************block********************* -->
<div class="blocks-promo">
    <div class="block-promo style-guide-block">
        <img src="{{media url="wysiwyg/gear/gear-equipment.jpg"}}" alt="">
        <a class="action shop-btn more icon">Shop Performance</a>
    </div>
</div>