<!-- home-page-slider -->

<div class="homepage-slider some-block">
    <div class="homepage-slide">
            <div class="some-img">
                <img src="{{media url="wysiwyg//home/home-main.jpg"}}" alt="">
            </div>
        <span class="block-content">
            <strong class="block-title">
                Outdoor Dining
            </strong>
            <span class ="block-info">
                Get summer ready with <br> our exclusive outdoor funiture
            </span>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP OUTDOOR DAYBEDS</a>
        </span> 
    </div>
    <div class="homepage-slide">
            <div class="some-img">
                <img src="{{media url="wysiwyg/slider/Image1.png"}}" alt="">
            </div>
        <span class="block-content">
            <strong class="block-title">
                Outdoor Dining
            </strong>
            <span class ="block-info">
                Get summer ready with <br> our exclusive outdoor funiture
            </span>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP OUTDOOR DAYBEDS</a>
        </span> 
    </div>
    <div class="homepage-slide">
        <span class="block-content">
            <strong class="block-title">
                Outdoor Dining
            </strong>
            <span class ="block-info">
                Get summer ready with <br> our exclusive outdoor funiture
            </span>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP OUTDOOR DAYBEDS</a>
        </span> 
    </div>
</div>



<!-- shop-now-block -->
<div class="block-shop-now-wrapper row"> 
    <div class="block-shop-now  some-block col-mb-6"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/shop-now/Image1.png"}}" alt="">
        </div>
        <span class="block-content">
            <strong class="block-title">
                OUTDOOR DINING
            </strong>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP NOW</a>
        </span> 
    </div>
    <div class="block-shop-now  some-block col-mb-6"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/shop-now/Image2.png"}}" alt="">
        </div>
        <span class="block-content">
            <strong class="block-title">
                OUTDOOR LOUNGES
            </strong>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP NOW</a>
        </span> 
    </div>
</div>


<!-- reason-to-buy -->
<div class="reason-to-buy-block some-block">
    <div class="reason-to-buy">
        <a class="action more icon" href="{{store url=""}}#">OUTDOOR FUNITURE CLEARANCE STORE</a>
    </div>
    <div class="reason-to-buy">
        <a class="action more icon" href="{{store url=""}}#">WE SHIP AUSTRALIA WIDE</a>
    </div>
    <div class="reason-to-buy">
        <a class="action more icon" href="{{store url=""}}#">30 DAY MONEY BACK GUARANTEE</a>
    </div>

</div>



<!-- block-banner -->
<div class="block-banner-wrapper row">
    <div class="block-banner some-block col-mb-4"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/block-banner/Image1.png"}}" alt="">
        </div>
        <div class="block-content-expansion">
            <span class="block-content">
                <strong class="block-title">
                    Vogue Collection
                </strong>
                <span class ="block-info">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.
                </span>
                <a class="action shop-btn more icon">SHOP NOW</a>
            </span> 
        </div>
    </div>
    <div class="block-banner some-block col-mb-4"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/block-banner/Image2.png"}}" alt="">
        </div>
        <div class="block-content-expansion">
            <span class="block-content">
                <strong class="block-title">
                    Maldives Collection
                </strong>
                <span class ="block-info">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.
                </span>
                <a class="action shop-btn more icon">SHOP NOW</a>
            </span> 
        </div>
    </div>
    <div class="block-banner some-block col-mb-4"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/block-banner/Image3.png"}}" alt="">
        </div>
        <div class="block-content-expansion">
            <span class="block-content">
                <strong class="block-title">
                    Marseilles Collection
                </strong>
                <span class ="block-info">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.
                </span>
                <a class="action shop-btn more icon">SHOP NOW</a>
            </span> 
        </div>
    </div>
</div>


<div class="video-block-slider">
    <div class="video-block some-block"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/video/Image1.png"}}" alt="">
        </div>
        <span class="block-content">
            <strong class="block-title">
                CATALOGUES
            </strong>
            <a class="action shop-btn more icon" href="{{store url=""}}#">EXPLORE NOW</a>
        </span> 
    </div> 
    <div class="video-block some-block"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/video/Image1.png"}}" alt="">
        </div>
        <div class="some-video">
            <iframe width="100%" height="100%" src="https://www.youtube.com/embed/L5cgVAItXgc?autoplay=1" frameborder="0" allowfullscreen="allowfullscreen">
            </iframe>
        </div>
    </div> 
</div>



<!-- best seller -->
<div class="my-content-heading some-block">
    <h1 class="title">Best Sellers</h1>
</div>
<p class="some-block">
    {{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="8" template="Magento_CatalogWidget::product/widget/content/slick.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`41`^]^]"}}
</p>

<!-- new arrivel -->
<div class="my-content-heading some-block">
    <h1 class="title">New Arrivals</h1>
</div>
<p class="some-block">
    {{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="8" template="Magento_CatalogWidget::product/widget/content/slick.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`41`^]^]"}}
</p>

<!-- instagram -->
<div class="instagram-block-wrapper">
    <div class="instagram-block-heading some-block">
        <div class="my-content-heading">
            <h1 class="title title-1">Outdoor inspiration with our instagram</h1>
            <h1 class="title title-2">Get inspried with instgram</h1>
        </div>
        <span class="find-us">
            Find us at @burninglog, show us your furniture with #buringlog
        </span>
    </div>
    <div class="instagram-block some-block">
        
        <div class="instagram-slide some-block">
            <div class="some-img">
                <img src="{{media url="wysiwyg/instagram-block/1.png"}}" alt="">
            </div>
        </div>
        <div class="instagram-slide some-block">
            <div class="some-img">
                <img src="{{media url="wysiwyg/instagram-block/1.png"}}" alt="">
            </div>
        </div>
        <div class="instagram-slide some-block">
            <div class="some-img">
                <img src="{{media url="wysiwyg/instagram-block/1.png"}}" alt="">
            </div>
        </div>
        <div class="instagram-slide some-block">
            <div class="some-img">
                <img src="{{media url="wysiwyg/instagram-block/1.png"}}" alt="">
            </div>
        </div>
        <div class="instagram-slide some-block">
            <div class="some-img">
                <img src="{{media url="wysiwyg/instagram-block/1.png"}}" alt="">
            </div>
        </div>
        <div class="instagram-slide some-block">
            <div class="some-img">
                <img src="{{media url="wysiwyg/instagram-block/1.png"}}" alt="">
            </div>
        </div>
    </div>
    <div class="link-button some-block"> 
        <a class="action tocart secondary" href="{{store url=""}}#">VIEW OUR INSTAGRAM</a>
    </div>

</div>
