<!-- Footer links mobile-->
<div class="footer-links-mobile" id="accordion" data-mage-init='{
        "accordion":{
            "active": [1, 2],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
    <div data-role="collapsible">
        <div data-role="trigger">
            <h3>Category</h3>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
            </li>
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}
            </li>
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}
            </li>
        </ul>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h3>Why Burning Log?</h3>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
            </li>
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}
            </li>
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}
            </li>
        </ul>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">
            <h3>Our Policies</h3>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li><a>Subscribe to our newsletter for the latest news and updates</a></li>
        </ul>
    </div>
</div>
<!-- End Footer links mobile-->