<!-- nav icon -->
<div class="nav-footer-icon">
    <div class="icon-item">
        <div class="social-icon"><a href="#"><i class="fab fa-facebook-f"></i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-instagram"></i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-twitter"></i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-brands fa-youtube"></i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-brands fa-pinterest"></i></a></div>
    </div>
</div>
<!-- end nav icon -->