<!-- footer top -->
<div class="footer-top">
    <div class="row">
        <div class="col-3 col-sm-6">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-truck"></i>
                </div>
                <span class="text">We ship australia wide!</span>
            </div>
        </div>
        <div class="col-3 col-sm-6">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-location-dot"></i>
                </div>
                <span class="text">Find a store</span>
            </div>
        </div>
        <div class="col-3 col-sm-6">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-dollar-sign"></i>
                </div>
                <span class="text">Money back guarantee</span>
            </div>
        </div>
        <div class="col-3 col-sm-6">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-envelope"></i>
                </div>
                <span class="text">Contact us</span>
            </div>
        </div>
    </div>
</div>
<!-- end footer top -->