<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-bottom">
    <small class="copyright">
        <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
    </small>
    <?php
    echo $block->getLayout()

        ->createBlock('Magento\Cms\Block\Block')

        ->setBlockId('img-logo-footer')

        ->toHtml();
    ?>
</div>