<!-- Showrom -->
<div class="session-showrom">
    <div class="row">
        <div class="col-4">
            <div class="showrom-img some-img"><img
                    src="{{media url="wysiwyg/image_showroom_footer/outdoor_Elegance.png"}}"
                    alt="Outdoor Elegance Logo"></div>
        </div>
        <div class="col-4">
            <div class="showrom-Canberra"><a class="canberra-link action secondary" href="#">Canberra Showroom</a>
                <div class="style-guide-paragraph">
                    <p>Maryborough St &amp; Wollongong Street, Fyshwick ACT 2609 T: 1300 6</p>
                </div>
                <a class="web-link links-info" href="#">Text link</a>
            </div>
        </div>
        <div class="col-4">
            <div class="showrom-img some-img"><img src="{{media url="wysiwyg/image_showroom_footer/webstore_logo.png"}}"
                    alt="Web Store Logo"></div>
        </div>
    </div>
</div>
<!-- End showrom -->
<!-- Footer banner-->
<div class="session-footer-banner">
    <div class="footer-banner backgroud-img">
        <div class="content-banner">
            <h1 class="title-banner">Exclusive outdoor furniture, online prices</h1>
            <div class="style-guide-paragraph">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua.<a class="web-link links-banner" href="#">Learn more</a></p>
            </div>
        </div>
    </div>
</div>
<!-- End footer banner-->